/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthService_GetJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthService_LoginPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthService_SetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["AuthService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/order/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of a customer's orders.
         *     If accessed through the gateway - shows the current user's orders. */
        get: operations["OrderService_ViewOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/order/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderService_ViewOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/order/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrderService_PlaceOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/order/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["OrderService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment/balance/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentService_ViewBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["PaymentService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment/transaction/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentService_ViewTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/product/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductService_ViewProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/product/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["ProductService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductService_ViewProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipping/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["ShippingService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipping/shipment/{shipmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShippingService_ViewShipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipping/shipment/{shipmentId}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShippingService_ViewShipmentManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserService_RegisterUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["UserService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_ViewUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouse/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WarehouseService_ViewProductStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouse/reservation/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WarehouseService_ViewReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouse/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View information about the service.
         * @description buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
         */
        get: operations["WarehouseService_ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "@type": "@type"
         *     } */
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: Record<string, never>;
        };
        /** @example {
         *       "code": 0,
         *       "details": [
         *         {
         *           "@type": "@type"
         *         },
         *         {
         *           "@type": "@type"
         *         }
         *       ],
         *       "message": "message"
         *     } */
        rpcStatus: {
            /** Format: int32 */
            code?: number;
            message?: string;
            details?: components["schemas"]["protobufAny"][];
        };
        /** @example {
         *       "expiresIn": "expiresIn",
         *       "tokenType": "tokenType",
         *       "accessToken": "accessToken"
         *     } */
        v1AuthToken: {
            tokenType?: string;
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: string;
        };
        /** @example {
         *       "balance": 0.8008282,
         *       "customerId": "customerId"
         *     } */
        v1CustomerBalance: {
            customerId?: string;
            /** Format: float */
            balance?: number;
        };
        /** @example {
         *       "keys": [
         *         {
         *           "kty": "kty",
         *           "use": "use",
         *           "crv": "crv",
         *           "x": "x",
         *           "y": "y",
         *           "alg": "alg"
         *         },
         *         {
         *           "kty": "kty",
         *           "use": "use",
         *           "crv": "crv",
         *           "x": "x",
         *           "y": "y",
         *           "alg": "alg"
         *         }
         *       ]
         *     } */
        v1GetJwksResponse: {
            keys?: components["schemas"]["v1PublicEcJWK"][];
        };
        v1LoginPasswordRequest: {
            userId: string;
            password: string;
        };
        /** @example {
         *       "data": {
         *         "expiresIn": "expiresIn",
         *         "tokenType": "tokenType",
         *         "accessToken": "accessToken"
         *       },
         *       "detail": "detail"
         *     } */
        v1LoginPasswordResponse: {
            detail?: string;
            data?: components["schemas"]["v1AuthToken"];
        };
        /** @example {
         *       "createdAt": "createdAt",
         *       "shippingId": "shippingId",
         *       "customerId": "customerId",
         *       "id": "id",
         *       "items": {
         *         "key": 0
         *       },
         *       "transactionId": "transactionId",
         *       "status": "ORDER_STATUS_UNSPECIFIED",
         *       "updatedAt": "updatedAt"
         *     } */
        v1Order: {
            id?: string;
            status?: components["schemas"]["v1OrderStatus"];
            /** @description 'items' consists of a mapping of Product ID to Quantity. */
            items?: {
                [key: string]: number;
            };
            customerId?: string;
            transactionId?: string;
            shippingId?: string;
            /** Format: int64 */
            createdAt?: string;
            /** Format: int64 */
            updatedAt?: string;
        };
        /**
         * - ORDER_STATUS_PROCESSING: awaiting price quotes for products
         *      - ORDER_STATUS_PENDING: awaiting stock allocation, shipping allotment and payment
         * @default ORDER_STATUS_UNSPECIFIED
         * @enum {string}
         */
        v1OrderStatus: "ORDER_STATUS_UNSPECIFIED" | "ORDER_STATUS_PROCESSING" | "ORDER_STATUS_PENDING" | "ORDER_STATUS_REJECTED" | "ORDER_STATUS_APPROVED" | "ORDER_STATUS_COMPLETED";
        /** @example {
         *       "order": {
         *         "createdAt": "createdAt",
         *         "shippingId": "shippingId",
         *         "customerId": "customerId",
         *         "id": "id",
         *         "items": {
         *           "key": 0
         *         },
         *         "transactionId": "transactionId",
         *         "status": "ORDER_STATUS_UNSPECIFIED",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1PlaceOrderResponse: {
            order?: components["schemas"]["v1Order"];
        };
        /** @example {
         *       "createdAt": "createdAt",
         *       "price": 0.8008282,
         *       "name": "name",
         *       "description": "description",
         *       "id": "id",
         *       "updatedAt": "updatedAt"
         *     } */
        v1Product: {
            id?: string;
            name?: string;
            description?: string;
            /** Format: float */
            price?: number;
            /** Format: int64 */
            createdAt?: string;
            /** Format: int64 */
            updatedAt?: string;
        };
        /** @example {
         *       "quantity": 0,
         *       "productId": "productId"
         *     } */
        v1ProductStock: {
            productId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        /** @example {
         *       "kty": "kty",
         *       "use": "use",
         *       "crv": "crv",
         *       "x": "x",
         *       "y": "y",
         *       "alg": "alg"
         *     } */
        v1PublicEcJWK: {
            kty?: string;
            use?: string;
            alg?: string;
            crv?: string;
            x?: string;
            y?: string;
        };
        /** @example {
         *       "user": {
         *         "firstName": "firstName",
         *         "lastName": "lastName",
         *         "createdAt": "createdAt",
         *         "id": "id",
         *         "email": "email",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1RegisterUserResponse: {
            user?: components["schemas"]["v1User"];
        };
        /** @example {
         *       "createdAt": "createdAt",
         *       "orderId": "orderId",
         *       "reservedStock": [
         *         {
         *           "quantity": 0,
         *           "productId": "productId"
         *         },
         *         {
         *           "quantity": 0,
         *           "productId": "productId"
         *         }
         *       ],
         *       "id": "id"
         *     } */
        v1Reservation: {
            id?: string;
            orderId?: string;
            reservedStock?: components["schemas"]["v1ReservationStock"][];
            /** Format: int64 */
            createdAt?: string;
        };
        /** @example {
         *       "quantity": 0,
         *       "productId": "productId"
         *     } */
        v1ReservationStock: {
            productId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        /** @example {
         *       "sourceLicense": "sourceLicense",
         *       "name": "name",
         *       "source": "source"
         *     } */
        v1ServiceInfoResponse: {
            name?: string;
            source?: string;
            sourceLicense?: string;
        };
        v1SetPasswordRequest: {
            userId: string;
            password: string;
        };
        /** @example {
         *       "detail": "detail"
         *     } */
        v1SetPasswordResponse: {
            detail?: string;
        };
        /** @example {
         *       "createdAt": "createdAt",
         *       "dispatched": true,
         *       "orderId": "orderId",
         *       "id": "id",
         *       "updatedAt": "updatedAt"
         *     } */
        v1Shipment: {
            id?: string;
            orderId?: string;
            dispatched?: boolean;
            /** Format: int64 */
            createdAt?: string;
            /** Format: int64 */
            updatedAt?: string;
        };
        /** @example {
         *       "quantity": 0,
         *       "productId": "productId",
         *       "shipmentId": "shipmentId"
         *     } */
        v1ShipmentItem: {
            shipmentId?: string;
            productId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        /** @example {
         *       "amount": 0.8008282,
         *       "orderId": "orderId",
         *       "reversedAt": "reversedAt",
         *       "customerId": "customerId",
         *       "processedAt": "processedAt",
         *       "id": "id"
         *     } */
        v1Transaction: {
            id?: string;
            /** Format: float */
            amount?: number;
            orderId?: string;
            customerId?: string;
            /**
             * Format: int64
             * @description Optional - If set, then the transaction has been refunded.
             */
            reversedAt?: string;
            /** Format: int64 */
            processedAt?: string;
        };
        /** @example {
         *       "firstName": "firstName",
         *       "lastName": "lastName",
         *       "createdAt": "createdAt",
         *       "id": "id",
         *       "email": "email",
         *       "updatedAt": "updatedAt"
         *     } */
        v1User: {
            id?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            /** Format: int64 */
            createdAt?: string;
            /** Format: int64 */
            updatedAt?: string;
        };
        /** @example {
         *       "balance": {
         *         "balance": 0.8008282,
         *         "customerId": "customerId"
         *       }
         *     } */
        v1ViewBalanceResponse: {
            balance?: components["schemas"]["v1CustomerBalance"];
        };
        /** @example {
         *       "order": {
         *         "createdAt": "createdAt",
         *         "shippingId": "shippingId",
         *         "customerId": "customerId",
         *         "id": "id",
         *         "items": {
         *           "key": 0
         *         },
         *         "transactionId": "transactionId",
         *         "status": "ORDER_STATUS_UNSPECIFIED",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1ViewOrderResponse: {
            order?: components["schemas"]["v1Order"];
        };
        /** @example {
         *       "orders": [
         *         {
         *           "createdAt": "createdAt",
         *           "shippingId": "shippingId",
         *           "customerId": "customerId",
         *           "id": "id",
         *           "items": {
         *             "key": 0
         *           },
         *           "transactionId": "transactionId",
         *           "status": "ORDER_STATUS_UNSPECIFIED",
         *           "updatedAt": "updatedAt"
         *         },
         *         {
         *           "createdAt": "createdAt",
         *           "shippingId": "shippingId",
         *           "customerId": "customerId",
         *           "id": "id",
         *           "items": {
         *             "key": 0
         *           },
         *           "transactionId": "transactionId",
         *           "status": "ORDER_STATUS_UNSPECIFIED",
         *           "updatedAt": "updatedAt"
         *         }
         *       ]
         *     } */
        v1ViewOrdersResponse: {
            orders?: components["schemas"]["v1Order"][];
        };
        /** @example {
         *       "product": {
         *         "createdAt": "createdAt",
         *         "price": 0.8008282,
         *         "name": "name",
         *         "description": "description",
         *         "id": "id",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1ViewProductResponse: {
            product?: components["schemas"]["v1Product"];
        };
        /** @example {
         *       "stock": {
         *         "quantity": 0,
         *         "productId": "productId"
         *       }
         *     } */
        v1ViewProductStockResponse: {
            stock?: components["schemas"]["v1ProductStock"];
        };
        /** @example {
         *       "products": [
         *         {
         *           "createdAt": "createdAt",
         *           "price": 0.8008282,
         *           "name": "name",
         *           "description": "description",
         *           "id": "id",
         *           "updatedAt": "updatedAt"
         *         },
         *         {
         *           "createdAt": "createdAt",
         *           "price": 0.8008282,
         *           "name": "name",
         *           "description": "description",
         *           "id": "id",
         *           "updatedAt": "updatedAt"
         *         }
         *       ]
         *     } */
        v1ViewProductsResponse: {
            products?: components["schemas"]["v1Product"][];
        };
        /** @example {
         *       "reservation": {
         *         "createdAt": "createdAt",
         *         "orderId": "orderId",
         *         "reservedStock": [
         *           {
         *             "quantity": 0,
         *             "productId": "productId"
         *           },
         *           {
         *             "quantity": 0,
         *             "productId": "productId"
         *           }
         *         ],
         *         "id": "id"
         *       }
         *     } */
        v1ViewReservationResponse: {
            reservation?: components["schemas"]["v1Reservation"];
        };
        /** @example {
         *       "manifest": [
         *         {
         *           "quantity": 0,
         *           "productId": "productId",
         *           "shipmentId": "shipmentId"
         *         },
         *         {
         *           "quantity": 0,
         *           "productId": "productId",
         *           "shipmentId": "shipmentId"
         *         }
         *       ]
         *     } */
        v1ViewShipmentManifestResponse: {
            manifest?: components["schemas"]["v1ShipmentItem"][];
        };
        /** @example {
         *       "shipment": {
         *         "createdAt": "createdAt",
         *         "dispatched": true,
         *         "orderId": "orderId",
         *         "id": "id",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1ViewShipmentResponse: {
            shipment?: components["schemas"]["v1Shipment"];
        };
        /** @example {
         *       "transaction": {
         *         "amount": 0.8008282,
         *         "orderId": "orderId",
         *         "reversedAt": "reversedAt",
         *         "customerId": "customerId",
         *         "processedAt": "processedAt",
         *         "id": "id"
         *       }
         *     } */
        v1ViewTransactionResponse: {
            transaction?: components["schemas"]["v1Transaction"];
        };
        /** @example {
         *       "user": {
         *         "firstName": "firstName",
         *         "lastName": "lastName",
         *         "createdAt": "createdAt",
         *         "id": "id",
         *         "email": "email",
         *         "updatedAt": "updatedAt"
         *       }
         *     } */
        v1ViewUserResponse: {
            user?: components["schemas"]["v1User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthService_GetJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetJwksResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_LoginPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1LoginPasswordRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1LoginPasswordResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_SetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1SetPasswordRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SetPasswordResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrderService_ViewOrders: {
        parameters: {
            query?: {
                customerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewOrdersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrderService_ViewOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewOrderResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrderService_PlaceOrder: {
        parameters: {
            query?: {
                customerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: number;
                };
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PlaceOrderResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrderService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PaymentService_ViewBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewBalanceResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PaymentService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PaymentService_ViewTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewTransactionResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ProductService_ViewProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewProductsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ProductService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ProductService_ViewProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewProductResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ShippingService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ShippingService_ViewShipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewShipmentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ShippingService_ViewShipmentManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewShipmentManifestResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_RegisterUser: {
        parameters: {
            query: {
                firstName: string;
                lastName: string;
                email: string;
                password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RegisterUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_ViewUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    WarehouseService_ViewProductStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewProductStockResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    WarehouseService_ViewReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ViewReservationResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    WarehouseService_ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ServiceInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
}
